name: Project Validation

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Validate Basic Files
        run: |
          test -f README.md
          test -f metadata.yml
          test -f BOM.csv
          test -d CAD
          test -d docs
          test -f docs/Assembly_Instructions.pdf
