name: Check Project Files

on: [push]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check essential files
        run: |
          for file in README.md LICENSE metadata.yml docs/Assembly_Instructions.pdf; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing: $file"
              exit 1
            fi
          done
          echo "✅ All essential files exist"
