name: Project Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Structure and Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for broken links in HTML
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          folder-path: 'docs'

      - name: Validate metadata.yml
        run: |
          echo "Validating YAML..."
          python3 -c "import yaml, sys; yaml.safe_load(open('metadata.yml'))" || exit 1

      - name: Check if key files exist
        run: |
          test -f "README.md" || (echo "Missing README.md" && exit 1)
          test -f "LICENSE" || (echo "Missing LICENSE" && exit 1)
          test -f "index.html" || (echo "Missing index.html" && exit 1)
          test -f "metadata.yml" || (echo "Missing metadata.yml" && exit 1)

      - name: List CAD and PDF files
        run: |
          echo "CAD files:"
          find CAD -type f
          echo "PDF files:"
          find docs -name '*.pdf'
